### ISSUE TITLE
Typecheck fails when importing from a project with stricter tsconfig

### ISSUE THREAD

**Issue by rickyrombo** [paulmillr/micro-aes-gcm#4]
Hi @paulmillr ! 👋 

Merry Christmas if you celebrate!
      
Firstly, thanks for your work on this project! Also huge shoutout, love the noble packages too! 😄 

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `micro-aes-gcm@0.3.3` for the project I'm working on.

I have a typescript project that uses [@tsconfig/node16-strictest](https://github.com/tsconfig/bases/blob/main/bases/node16-strictest-esm.combined.json) and it seems like the defaults there are stricter than what this package uses. I added a few changes to make the typecheck happy in my project - mostly just assertions that don't affect anything at runtime, but one access change from `.crypto` to `['crypto']`.

Just thought I'd let you know, definitely not high priority to fix but leaving this here for others to help them if they run into the same thing.

Also, unrelated, but any chance this could also export as Common JS?

Here are the errors that I got:

```
> tsc --noEmit

node_modules/micro-aes-gcm/index.ts(7,60): error TS4111: Property 'crypto' comes from an index signature, so it must be accessed with ['crypto'].
node_modules/micro-aes-gcm/index.ts(32,28): error TS2322: Type 'Uint8Array | undefined' is not assignable to type 'Uint8Array'.
  Type 'undefined' is not assignable to type 'Uint8Array'.
node_modules/micro-aes-gcm/index.ts(37,16): error TS2345: Argument of type 'Uint8Array | undefined' is not assignable to parameter of type 'ArrayLike<number>'.
  Type 'undefined' is not assignable to type 'ArrayLike<number>'.
node_modules/micro-aes-gcm/index.ts(38,12): error TS2532: Object is possibly 'undefined'.
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/micro-aes-gcm/index.ts b/node_modules/micro-aes-gcm/index.ts
index 07c24fe..d6ca0f0 100644
--- a/node_modules/micro-aes-gcm/index.ts
+++ b/node_modules/micro-aes-gcm/index.ts
@@ -4,7 +4,7 @@ import * as nodeCrypto from 'crypto';
 declare const self: Record<string, any> | undefined;
 const crypto = {
   node: nodeCrypto,
-  web: typeof self === 'object' && 'crypto' in self ? self.crypto : undefined,
+  web: typeof self === 'object' && 'crypto' in self ? self['crypto'] : undefined,
 };
 
 // Caching slows it down 2-3x
@@ -29,11 +29,11 @@ function hexToBytes(hex: string): Uint8Array {
 function concatBytes(...arrays: Uint8Array[]): Uint8Array {
   if (!arrays.every((arr) => arr instanceof Uint8Array))
     throw new Error('Uint8Array list expected');
-  if (arrays.length === 1) return arrays[0];
+  if (arrays.length === 1) return arrays[0]!;
   const length = arrays.reduce((a, arr) => a + arr.length, 0);
   const result = new Uint8Array(length);
   for (let i = 0, pad = 0; i < arrays.length; i++) {
-    const arr = arrays[i];
+    const arr = arrays[i]!;
     result.set(arr, pad);
     pad += arr.length;
   }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by paulmillr** [comment]
Hey. Done.

>Also, unrelated, but any chance this could also export as Common JS?

No. Use bundlers.

Also i've switched to webcrypto-only. You'll need a shim for newer versions if you're using old nodejs.

**Comment by rickyrombo** [comment]
Thank you so much! And understood, thanks!
