### ISSUE TITLE
0.4.0 breaks working code

### ISSUE THREAD

**Issue by steida** [paulmillr/micro-aes-gcm#5]
I just updated to 0.4.0 from 0.3.3, and this error occurs:

<img width="453" alt="Screenshot 2023-03-18 at 20 26 20" src="https://user-images.githubusercontent.com/66249/226132938-f8ed70cd-d16e-4243-8af4-b96895b149fb.png">

What am I doing wrong? Thank you

**Comment by paulmillr** [comment]
AES-256 key must be 32 bytes. Seems like yours isnt?

**Comment by steida** [comment]
My key is bip39.generateMnemonic(wordlist, 128) converted via mnemonicToEntropy. So do I have to use 24 words? Is 12-words mnemonic too weak? Thank you

**Comment by paulmillr** [comment]
you can: 1) pad key to make it 32 bytes instead of 16 2) use `mnemonicToSeed` instead, which has better security for this use-case.

**Comment by steida** [comment]
@paulmillr Thank you. May I ask why it has better security? Do you mean with a password?

**Comment by steida** [comment]
I used `mnemonicToSeedSync` and the result is the same.

```Error: {"type":"UnknownError","error":{"message":"Uint8Array length 32 expected","stack":"Error: Uint8Array length 32 expected\n at ensureBytes```
